### ISSUE TITLE
Empty expression statement has no effect

### ISSUE THREAD

**Issue by ericwomer** [NVIDIAGameWorks/PhysX#3]
Fails to compiles on Ubuntu 18.04 with clang-8

```
PhysX/physx/../pxshared/include/foundation/unix/PxUnixIntrinsics.h:178:50: error: empty expression statement has no effect; remove unnecessary ';' to silence this
      warning [-Werror,-Wextra-semi-stmt]
        PX_ASSERT(((size_t(dest) + offset) & 0x7f) == 0);

```

**Comment by AlesBorovicka** [comment]
Hi,
 I dont see clang 8 release available yet. It should compile fine with up to clang 7. We will update to clang 8 in later updates.

**Comment by ericwomer** [comment]
Yes, you are correct, I don't know what happened between the clang 7 and 8, but it compiles now and the demos run, minus one cavete, a dependenct on glut3 thats not handled by cmake, it should warn that the demos depend on glut3, I ended up installing glut3 and it works fine.

**Comment by AlesBorovicka** [comment]
I see, will try to take a look at that, thanks for the report
