### PR TITLE
Fix compile error on Xcode 11

### LINKED ISSUE #183: Compile error with Xcode 11
Got a surprise update to Xcode 11 on my Mac today, and with the new compiler PhysX doesn't build anymore due to a new error being enabled by default:

```sh
PhysX/physx/source/foundation/include/unix/PsUnixIntrinsics.h:59:2: error: implicit use of sequentially-consistent atomic may incur stronger memory barriers than necessary [-Werror,-Watomic-implicit-seq-cst]
        __sync_synchronize();
        ^~~~~~~~~~~~~~~~~~
1 error generated.
```

This can be fixed, or rather worked around, by modifying the `physx/source/compiler/cmake/mac/CMakeLists.txt` and adding `-Wno-atomic-implicit-seq-cst` to the `SET(PHYSX_CXX_FLAGS` line.

Would it be possible to do get out a quick fix of this in this repo? Ran into this for our `physx-rs` Rust bindings (https://github.com/EmbarkStudios/physx-rs/issues/23) and that crate currently includes this repo as source to avoid modifying the actual PhysX code.

### PR DESCRIPTION
**Pull request by repi**
Disabled the `atomic-implicit-seq-cst` warning that seems to have been enabled by default going from Xcode 10 to 11 (and then new clang version).

This is tested to also compile on Xcode 10.3, which also had the warning but wasn't enabled by default.

Fixes #183 and https://github.com/EmbarkStudios/physx-rs/issues/23.

### CODE REVIEW

**Comment by AlesBorovicka** [comment]
Thanks, I have applied the patch into our main.

**Comment by repi** [comment]
Thanks
