### ISSUE TITLE
Unresolved external symbol with static library build (Win10; Visual studio 2019)

### ISSUE THREAD

**Issue by TheDonsky** [NVIDIAGameWorks/PhysX#423]
I'm attempting to integrate PhysX with my project and, for some reason, can not properly link static libraries.

The process I followed is as follows:
1. I cloned PhysX repository on my desktop;
2. Modified PhysX\physx\buildtools\presets\public\vc16win64.xml as follows:
PX_BUILDSNIPPETS = False; (Had a chance to familiarize myself with those separately)
PX_BUILDPUBLICSAMPLES = False; (Probably did not need samples)
PX_GENERATE_STATIC_LIBRARIES = True; (I'd rather statically link libs than carry dll-s around for this particular project)
NV_USE_STATIC_WINCRT = False; (May project uses multithreaded dll, so this should be my option)
NV_USE_DEBUG_WINCRT = True;
PX_FLOAT_POINT_PRECISE_MATH = False;
3. Generate the solution with PhysX\physx\generate_projects.bat (13) and build the generated solution with "Release" configuration;
4. Clone PhysX repository again, but, this time, as a submodule of my project;
5. Copy all .lib files from PhysX\physx\bin\win.x86_64.vc142.md\release to PhysX-Lib\MSVS_2019\x64\Release inside my project's repository;
6. Inside my project,  add "PhysX-Lib\MSVS_2019\x64\Release" to "project settings/Linker/General/Additional Library Dependencies";
7. Add following to "project settings/Linker/Input/Additional Dependencies":
PhysX_static_64.lib
PhysXCharacterKinematic_static_64.lib
PhysXCommon_static_64.lib
PhysXCooking_static_64.lib
PhysXExtensions_static_64.lib
PhysXFoundation_static_64.lib
PhysXPvdSDK_static_64.lib
PhysXVehicle_static_64.lib
8. Add following to "project settings/'C/C++'/General/Additional Include Directories":
PhysX\physx\include
PhysX\pxshared\include (PxErrorCallback was invisible without this one)
9. Try to build with Release/x64 configuration;
10. No matter what I do, I consistently get error: "error LNK2001: unresolved external symbol __imp_PxCreateFoundation";

Most other issues I found have stuff like conflicting runtime warnings, but I have none of that, just one linker error;
Here is my project's repository if you need more information: https://github.com/TheDonsky/Jimara.git
Only file that uses PhysX is "__Source__/Jimara-Tests/Components/PhysicsPlayground.cpp"

**Comment by AlesBorovicka** [comment]
Hi,
 did you include PxConfig.h? You need to either include this header before PxPhysicsAPI headers or you can add to your preprocessor defines PX_PHYSX_STATIC_LIB.
Hope that helps.
Regards,
Ales

**Comment by TheDonsky** [comment]
Hello,
Thanks a lot!
Was not aware of that header (the submodule does not contain it, since I made the build separately)
Added the definition for PX_PHYSX_STATIC_LIB and it worked.
Regards,
Nick
